version: '3.8'
services:
  api-gateway:
    image: api-gateway:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.api-gateway
    ports:
      - "8080:8080"
    environment:
      - APP_CUSTOMERS_URI=http://customers-service:8082
      - APP_VETS_URI=http://vets-service:8083
      - APP_VISITS_URI=http://visits-service:8084
    depends_on:
      - customers-service
      - vets-service
      - visits-service

  customers-service:
    image: customers-service:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.customers-service
    ports:
      - "8082:8082"
  
  vets-service:
    image: vets-service:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.vets-service
    ports:
      - "8083:8083"
  
  visits-service:
    image: visits-service:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.visits-service
    ports:
      - "8084:8084"
