apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  APP_CUSTOMERS_URI: "http://customers-service:8082"
  APP_VETS_URI: "http://vets-service:8083"
  APP_VISITS_URI: "http://visits-service:8084"
