# syntax=docker/dockerfile:1.2
FROM maven:3.6.3-jdk-8 AS build
WORKDIR /app

COPY pom.xml .
COPY spring-petclinic-api-gateway/ spring-petclinic-api-gateway/

WORKDIR /app/spring-petclinic-api-gateway
RUN mvn dependency:go-offline -B
RUN mvn clean package -DskipTests -B

FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /app/spring-petclinic-api-gateway/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
