# syntax=docker/dockerfile:1.2
FROM maven:3.6.3-jdk-8 AS build
WORKDIR /app

COPY pom.xml .
COPY spring-petclinic-visits-service/ spring-petclinic-visits-service/

WORKDIR /app/spring-petclinic-visits-service
RUN mvn dependency:go-offline -B
RUN mvn clean package -DskipTests -B

FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /app/spring-petclinic-visits-service/target/*.jar app.jar

EXPOSE 8084
ENTRYPOINT ["java", "-jar", "app.jar"]
