FROM maven:3.6.3-jdk-8 AS build
WORKDIR /app

COPY pom.xml .

COPY spring-petclinic-customers-service/ spring-petclinic-customers-service/

WORKDIR /app/spring-petclinic-customers-service

RUN mvn dependency:go-offline -B

RUN mvn clean package -DskipTests -B

FROM openjdk:8-jre-alpine
WORKDIR /app

COPY --from=build /app/spring-petclinic-customers-service/target/*.jar app.jar

EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]